# services:
#   kafka:
#     image: docker.io/apache/kafka:4.1.1
#     container_name: kafka-java-app
#     hostname: kafka
#     ports:
#       - "9292:9092"
#     environment:
#       KAFKA_NODE_ID: 1
#       KAFKA_PROCESS_ROLES: broker,controller
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://${HOST_PORT}:9092,CONTROLLER://0.0.0.0:9093
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://${HOST_PORT}:9092
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

#     volumes:
#       - kafka-data:/var/lib/kafka/data

#   kafka-ui:
#     image: docker.io/provectuslabs/kafka-ui:latest
#     container_name: kafka-java-app-ui
#     ports:
#       - "9090:8080"
#     environment:
#       KAFKA_CLUSTERS_0_NAME: local
#       KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${HOST_PORT}:9090
#     depends_on:
#       - kafka

# volumes:
#    kafka-data:

# services:
#   broker:
#     image: apache/kafka:4.1.1
#     container_name: broker
#     ports:
#       - "9292:9092"
#       - "9293:9093"
#     environment:
#       KAFKA_NODE_ID: 1
#       KAFKA_PROCESS_ROLES: broker,controller
#       KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
#       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#       KAFKA_NUM_PARTITIONS: 3

#   kafka-ui:
#     image: provectuslabs/kafka-ui:v0.7.2
#     container_name: kafka-ui
#     ports:
#       - "8092:8080"
#     environment:
#       DYNAMIC_CONFIG_ENABLED: "true"
#       KAFKA_CLUSTERS_0_NAME: local
#       KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
#     depends_on:
#       - broker

services:
  kafka-broker:
    image: apache/kafka:latest
    container_name: kafka-broker
    hostname: kafka-broker
    ports:
      - "9292:9092"
      - "9293:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://100.120.13.184:9292
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_RETENTION_HOURS: 168

      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test:
        [
          "CMD",
          "kafka-metadata-quorum.sh",
          "--bootstrap-server",
          "localhost:9092",
          "describe",
          "--status",
        ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 45s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka-broker:
        condition: service_healthy
    ports:
      - "8092:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 100.120.13.184:9292
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT

volumes:
  kafka-data:

