services:
  OpenTSDB:
    hostname: tsdb
    container_name: tsdb
    image: docker.io/petergrace/opentsdb-docker:latest
    environment:
      - WAITSECS=30
    ports:
      - 4242:4242
      - 60030:60030
    volumes:
      - "./data:/data/hbase"